import {readFileSync} from 'node:fs';
import {after,before,test} from 'node:test';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,collection,setDoc,getDoc,getDocs,query,where,updateDoc,deleteDoc,writeBatch} from 'firebase/firestore';
let env:Awaited<ReturnType<typeof initializeTestEnvironment>>;
let admin:any,supervisor:any,agent:any;
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-crm-llamadas',firestore:{rules:readFileSync('firestore.rules','utf8')}});admin=env.authenticatedContext('admin',{email:'reclutamientohac@gmail.com',email_verified:true}).firestore();supervisor=env.authenticatedContext('sup',{email:'sup@example.com',email_verified:true}).firestore();agent=env.authenticatedContext('agent',{email:'agent@example.com',email_verified:true}).firestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,'usuariosAutorizados','sup@example.com'),{activo:true,rol:'Supervisor'});await setDoc(doc(db,'usuariosAutorizados','agent@example.com'),{activo:true,rol:'Telemarketing',telemarketingVinculada:'GERAL'});await setDoc(doc(db,'usuariosAutorizados','reclutamientohac@gmail.com'),{activo:true});await setDoc(doc(db,'prospectos','mine'),{telemarketing:'GERAL'});await setDoc(doc(db,'prospectos','other'),{telemarketing:'IRENE'});await setDoc(doc(db,'gestiones','mine'),{idProspecto:'mine',telemarketing:'IRENE'});await setDoc(doc(db,'gestiones','other'),{idProspecto:'other',telemarketing:'GERAL'});await setDoc(doc(db,'reportesGuardados','shared'),{usuario:'reclutamientohac@gmail.com',compartido:true});await setDoc(doc(db,'reportesGuardados','private'),{usuario:'sup@example.com',compartido:false});});});
after(async()=>{await env?.cleanup();});
test('respaldo y restauración exclusivos del administrador',async()=>{for(const name of ['respaldos','logRestauraciones']){await assertSucceeds(setDoc(doc(admin,name,'test'),{fecha:'2026-10-06'}));await assertSucceeds(getDocs(collection(admin,name)));await assertFails(getDocs(collection(supervisor,name)));await assertFails(setDoc(doc(supervisor,name,'bad'),{}));await assertFails(getDocs(collection(agent,name)));}});
test('consulta de gestiones por prospecto asignado actual',async()=>{await assertSucceeds(getDoc(doc(agent,'gestiones','mine')));await assertFails(getDoc(doc(agent,'gestiones','other')));await assertSucceeds(getDocs(query(collection(agent,'gestiones'),where('idProspecto','in',['mine']))));await assertFails(getDocs(collection(agent,'gestiones')));await assertSucceeds(getDocs(collection(supervisor,'gestiones')));});
test('guardados: propio, compartido y prohibición de compartir por telemarketing',async()=>{await assertSucceeds(getDoc(doc(agent,'reportesGuardados','shared')));await assertFails(getDoc(doc(agent,'reportesGuardados','private')));await assertSucceeds(setDoc(doc(agent,'reportesGuardados','own'),{usuario:'agent@example.com',compartido:false}));await assertFails(setDoc(doc(agent,'reportesGuardados','bad'),{usuario:'agent@example.com',compartido:true}));await assertSucceeds(getDocs(query(collection(agent,'reportesGuardados'),where('usuario','==','agent@example.com'))));await assertSucceeds(getDocs(query(collection(agent,'reportesGuardados'),where('compartido','==',true))));});
test('cuenta administradora no se desactiva ni elimina',async()=>{await assertFails(updateDoc(doc(admin,'usuariosAutorizados','reclutamientohac@gmail.com'),{activo:false}));await assertFails(deleteDoc(doc(admin,'usuariosAutorizados','reclutamientohac@gmail.com')));});
test('auditoría exige usuario real y parámetros solo admin',async()=>{await assertSucceeds(setDoc(doc(agent,'auditoria','export'),{usuario:'agent@example.com',accion:'EXPORTAR'}));await assertFails(setDoc(doc(agent,'auditoria','spoof'),{usuario:'sup@example.com'}));await assertFails(setDoc(doc(supervisor,'settings','backupParameters'),{warningDays:1}));await assertSucceeds(setDoc(doc(admin,'settings','backupParameters'),{warningDays:7}));});
test('recrear faltantes en lote con bitácora atómica',async()=>{await assertSucceeds(setDoc(doc(admin,'prospectos','restore-test'),{telemarketing:'GERAL',nombre:'Ejemplo'}));await assertSucceeds(deleteDoc(doc(admin,'prospectos','restore-test')));const batch=writeBatch(admin);batch.set(doc(admin,'prospectos','restore-test'),{telemarketing:'GERAL',nombre:'Ejemplo'});batch.set(doc(admin,'logRestauraciones','restore-test'),{estado:'Completada',aplicados:1});await assertSucceeds(batch.commit());await assertSucceeds(getDoc(doc(admin,'prospectos','restore-test')));});

import {applyRestore} from '../src/stage78/restoreEngine';
import {encodeRecord,backupHash} from '../src/stage78/backupCodec';
import {generateSampleProspectos,generateSampleGestionesAndCitas} from '../src/sampleData';
import type {BackupFile} from '../src/stage78/types';
import assert from 'node:assert/strict';
test('motor real: respaldo, borrar muestras, recuperar solo faltantes y conservar modificaciones',async()=>{
 const ps=generateSampleProspectos('reclutamientohac@gmail.com').slice(0,4),records=ps.map(p=>encodeRecord(p.id,p));
 for(const r of records)await setDoc(doc(admin,'prospectos',r.id),r.data);
 const file:BackupFile={app:'CRM LLAMADAS',version:1,fecha:new Date().toISOString(),usuario:'reclutamientohac@gmail.com',collections:{prospectos:records,settings:[]}};file.hash=await backupHash(file);
 await deleteDoc(doc(admin,'prospectos',records[0].id));await deleteDoc(doc(admin,'prospectos',records[1].id));await updateDoc(doc(admin,'prospectos',records[2].id),{nombre:'Conservar cambio'});
 const current:any={prospectos:[]};for(const r of records.slice(2)){const snap=await getDoc(doc(admin,'prospectos',r.id));current.prospectos.push(encodeRecord(r.id,snap.data()!));}
 const result=await applyRestore(admin,'reclutamientohac@gmail.com',file,current,['prospectos'],'missing',false,false,new AbortController().signal,()=>{},'muestra.json');
 assert.equal(result.estado,'Completada');assert.equal(result.aplicados,2);assert.equal((await getDoc(doc(admin,'prospectos',records[2].id))).data()?.nombre,'Conservar cambio');assert.equal((await getDoc(doc(admin,'prospectos',records[0].id))).data()?.nombre,records[0].data.nombre);
});
test('motor real: conflicto posterior a vista previa detiene sin sobrescribir',async()=>{const currentRecord=encodeRecord('conflict',{telemarketing:'GERAL',nombre:'Antes'});await setDoc(doc(admin,'prospectos','conflict'),currentRecord.data);const file:BackupFile={app:'CRM LLAMADAS',version:1,fecha:new Date().toISOString(),usuario:'reclutamientohac@gmail.com',collections:{prospectos:[encodeRecord('conflict',{telemarketing:'GERAL',nombre:'Del respaldo'})],settings:[]}};await updateDoc(doc(admin,'prospectos','conflict'),{nombre:'Cambio simultáneo'});const result=await applyRestore(admin,'reclutamientohac@gmail.com',file,{prospectos:[currentRecord]},['prospectos'],'replace',false,false,new AbortController().signal,()=>{},'muestra.json');assert.equal(result.estado,'Detenida por error');assert.equal(result.aplicados,0);assert.equal((await getDoc(doc(admin,'prospectos','conflict'))).data()?.nombre,'Cambio simultáneo');});
test('motor real: cancelar después del primer lote informa aplicados y pendientes',async()=>{const records=Array.from({length:201},(_,i)=>encodeRecord('cancel'+i,{telemarketing:'GERAL',nombre:'Prueba '+i}));const file:BackupFile={app:'CRM LLAMADAS',version:1,fecha:new Date().toISOString(),usuario:'reclutamientohac@gmail.com',collections:{prospectos:records,settings:[]}};const controller=new AbortController();const result=await applyRestore(admin,'reclutamientohac@gmail.com',file,{prospectos:[]},['prospectos'],'missing',false,false,controller.signal,()=>controller.abort(),'muestra.json');assert.equal(result.estado,'Cancelada parcialmente');assert.equal(result.aplicados,200);assert.equal(result.pendientes,1);assert.equal((await getDoc(doc(admin,'prospectos','cancel200'))).exists(),false);});
