import assert from 'node:assert/strict';
import test from 'node:test';
import {initializeApp} from 'firebase/app';
import {getFirestore,Timestamp,GeoPoint,Bytes,doc} from 'firebase/firestore';
import {calculateReport,normalizeOwner,inspectCRMIntegrity,compareBackup} from '../src/businessRules';
import {generateSampleProspectos} from '../src/sampleData';
import {encodeRecord,decodeRecord,backupHash,validateBackup,buildRestorePlan} from '../src/stage78/backupCodec';
import type {ReportFilters,ReportData,BackupFile} from '../src/stage78/types';
const ps=generateSampleProspectos('reclutamientohac@gmail.com');
const filters:ReportFilters={desde:'2000-01-01',hasta:'2099-12-31',base:'fechaRecepcion',enfoque:'Actividad',periodo:'mes',values:{}};
const data:ReportData={prospectos:ps,gestiones:[],citas:[],ventas:[],retroalimentaciones:[]};
test('normalización y muestras con variantes',()=>{assert.equal(normalizeOwner(' María  Pérez '),normalizeOwner('maria perez'));assert.equal(normalizeOwner('  '),'sin propietario');const r=calculateReport(data,filters,['propietario']);assert.equal(r.rows.find(x=>normalizeOwner(x.groups[0])==='maria perez')?.metrics.prospectos,2);assert.equal(r.total.metrics.prospectos,ps.filter(p=>!p.archivado).length);});
test('aislamiento por asignación actual, sin vínculo falla cerrado',()=>{assert.equal(calculateReport(data,filters,['propietario'],'').total.metrics.prospectos,0);const r=calculateReport(data,filters,['propietario'],'GERAL');assert.ok(r.data.prospectos.every(p=>p.telemarketing==='GERAL'));});
test('actividad frente a cohorte y días locales LA',()=>{const p={...ps[0],id:'p',fechaRecepcion:'2026-09-01'},other={...ps[1],id:'old',fechaRecepcion:'2026-08-01'};const d:any={...data,prospectos:[p,other],gestiones:[{id:'g1',idProspecto:'p',fechaHora:'2026-10-02T01:00:00Z',efectivo:'Sí'},{id:'g2',idProspecto:'p',fechaHora:'2026-09-15T18:00:00Z',efectivo:'No'},{id:'g3',idProspecto:'old',fechaHora:'2026-09-15T18:00:00Z',efectivo:'Sí'}]};const f={...filters,desde:'2026-09-01',hasta:'2026-09-30'};const a=calculateReport(d,f,['propietario']),c=calculateReport(d,{...f,enfoque:'Cohorte'},['propietario']);assert.equal(a.total.metrics.contactos,2);assert.equal(a.total.metrics.contactados,2);assert.equal(a.total.metrics.prospectos,1);assert.equal(c.total.metrics.contactos,2);assert.equal(c.total.metrics.contactados,1);});
test('atribución, porcentajes, ventas canceladas y dinero',()=>{const p={...ps[0],id:'p',telemarketing:'GERAL'};const d:any={...data,prospectos:[p],gestiones:[{id:'g1',idProspecto:'p',fechaHora:p.creadoEn,efectivo:'Sí',telemarketing:'IRENE'},{id:'g2',idProspecto:'p',fechaHora:p.creadoEn,efectivo:'No'}],citas:[{id:'c1',idProspecto:'p',fechaCita:p.fechaRecepcion,fechaCreacion:p.creadoEn,estadoCita:'Realizada'}],ventas:[{id:'v1',idProspecto:'p',idCita:'c1',fechaReporte:p.fechaRecepcion,estado:'Aprobada',montoAprobado:200,bonoGenerado:3,bonoPagable:3},{id:'v2',idProspecto:'p',fechaReporte:p.fechaRecepcion,estado:'Cancelada',montoAprobado:999}],retroalimentaciones:[{id:'r',idCita:'c1',idProspecto:'p'}]};const r=calculateReport(d,filters,['telemarketing']);assert.equal(r.rows[0].groups[0],'GERAL');assert.equal(r.total.metrics.ventas,1);assert.equal(r.total.metrics.monto,200);assert.equal(r.total.metrics.pctEfectividad,.5);assert.equal(r.total.metrics.pendientes,0);assert.equal(calculateReport(data,filters,['fecha']).total.metrics.pctVenta,0);});
test('tipos, IDs, hash, secretos y archivos alterados',async()=>{const db=getFirestore(initializeApp({projectId:'demo-codec'},'codec'));const raw={fecha:new Timestamp(1791280800,123456789),geo:new GeoPoint(34,-118),bytes:Bytes.fromUint8Array(new Uint8Array([1,2])),ref:doc(db,'prospectos','otro'),telefono:'0012345678'};const record=encodeRecord('p',raw),restored=decodeRecord(record,db);assert.equal(restored.fecha.toMillis(),raw.fecha.toMillis());assert.equal(restored.fecha.nanoseconds,raw.fecha.nanoseconds);assert.equal(restored.ref.path,raw.ref.path);assert.equal(restored.telefono,'0012345678');assert.deepEqual(restored.bytes.toUint8Array(),raw.bytes.toUint8Array());const file:BackupFile={app:'CRM LLAMADAS',version:1,fecha:new Date().toISOString(),usuario:'admin',collections:{prospectos:[record],settings:[]}};file.hash=await backupHash(file);await validateBackup(JSON.parse(JSON.stringify(file)));const corrupt=structuredClone(file);corrupt.collections.prospectos[0].data.nombre='Otra';await assert.rejects(validateBackup(corrupt),/hash/);assert.throws(()=>encodeRecord('bad',{accessToken:'secret'}),/autenticación/);});
test('respaldo de muestras, eliminación simulada y recuperar faltantes sin sobrescribir',async()=>{const records=ps.map(p=>encodeRecord(p.id,p));const file:BackupFile={app:'CRM LLAMADAS',version:1,fecha:new Date().toISOString(),usuario:'admin',collections:{prospectos:records,settings:[],usuariosAutorizados:[encodeRecord('reclutamientohac@gmail.com',{activo:false}),encodeRecord('a@example.com',{activo:true})]}};file.hash=await backupHash(file);await validateBackup(file);const current={prospectos:records.slice(3).map((p,i)=>i===0?{...p,data:{...p.data,nombre:'Modificado después'}}:p),settings:[],usuariosAutorizados:[]};const before=structuredClone(current.prospectos);assert.equal(compareBackup(file.collections,current)[0].nuevos,3);const plan=buildRestorePlan(file,current,['prospectos','usuariosAutorizados'],'missing',false,false);assert.equal(plan.length,3);const map=new Map(current.prospectos.map(r=>[r.id,r]));plan.forEach(op=>map.set(op.id,op.record!));assert.equal(map.size,records.length);assert.deepEqual(map.get(before[0].id),before[0]);assert.ok(buildRestorePlan(file,current,['usuariosAutorizados'],'replace',true,true).every(op=>op.id!=='reclutamientohac@gmail.com'));});
test('integridad sin correcciones automáticas',()=>{const p={...ps[0],id:'p'};const d:any={prospectos:[p,{...p,id:'p2'}],gestiones:[{id:'g',idProspecto:'absent'}],citas:[{id:'c',idProspecto:'p',fechaCita:'2026-02-31'}],ventas:[{id:'v',idProspecto:'p',idCita:'absent',estado:'Aprobada',montoAprobado:null,porcentajeBono:null}],retroalimentaciones:[]};const issues=inspectCRMIntegrity(d,['GERAL']);assert.ok(issues.some(i=>i.problema==='Gestión sin prospecto'));assert.equal(issues.filter(i=>i.problema==='Teléfono duplicado').length,2);assert.ok(issues.some(i=>i.problema==='Cita con fecha inválida'));assert.ok(issues.some(i=>i.problema.includes('sin monto')));});
test('30.000 prospectos y 100.000 gestiones',()=>{const big:any={prospectos:Array.from({length:30000},(_,i)=>({...ps[0],id:'p'+i,propietario:'Dueño '+i%50,telefono:String(i+2000000000)})),gestiones:Array.from({length:100000},(_,i)=>({id:'g'+i,idProspecto:'p'+i%30000,fechaHora:ps[0].creadoEn,efectivo:i%2?'Sí':'No'})),citas:[],ventas:[],retroalimentaciones:[]};const start=performance.now(),r=calculateReport(big,filters,['propietario']);console.log(`Cálculo 30k / 100k: ${Math.round(performance.now()-start)} ms`);assert.equal(r.total.metrics.prospectos,30000);assert.equal(r.total.metrics.contactos,100000);assert.equal(r.total.metrics.contactados,30000);assert.equal(r.rows.length,50);});

test('migración histórica conserva vínculos, pagos e idempotencia',async()=>{
 const {validateMigration}=await import('../src/stage78/migrationCodec.ts');const {prepareHistoricalMigration,calculateBonoPagable}=await import('../src/businessRules.ts');
 const p:any={formato:'CRM LLAMADAS - PAQUETE DE MIGRACION',version:1,zonaHoraria:'America/Los_Angeles',fecha:'2026-10-06T12:00:00Z',idLote:'MIG-TEST',colecciones:{prospectos:[{...ps[0],id:'old',telefono:'1234567890',intentos:4,contactosEfectivos:2}],citas:[{id:'c',idProspecto:'old',fechaCita:'2026-10-06',idEventoCalendar:'event'}],ventas:[{id:'v',idProspecto:'old',idCita:'c',estado:'Aprobada',montoAprobado:1000,porcentajeBono:0.01,bonoGenerado:10,bonoPagable:10,estadoPagoHistorico:'Pagada'}],retroalimentaciones:[]}};
 const pkg=validateMigration(p);const now:any={prospectos:[{id:'existing',data:{...p.colecciones.prospectos[0],id:'existing'}}]};const before=structuredClone(now);
 const plan=prepareHistoricalMigration(pkg,now,'admin');assert.equal(plan.remapped,1);assert.equal(plan.file.collections.prospectos.length,0);assert.equal(plan.file.collections.citas[0].data.idProspecto,'existing');assert.equal(plan.file.collections.ventas[0].data.bonoPagable,0);assert.equal(calculateBonoPagable('Aprobada',10,'Pagada'),0);
 const current={...plan.file.collections,prospectos:now.prospectos};assert.ok(prepareHistoricalMigration(pkg,current,'admin').rows.every(r=>r.nuevos===0));assert.deepEqual(now,before);
 const ambiguous=prepareHistoricalMigration(pkg,{prospectos:[{id:'a',data:{...p.colecciones.prospectos[0],nombre:'Otra persona'}}]},'admin');assert.equal(ambiguous.file.collections.citas.length,0);assert.ok(ambiguous.conflicts.length);
 assert.throws(()=>validateMigration({...p,colecciones:{...p.colecciones,usuariosAutorizados:[]}}));assert.throws(()=>validateMigration({...p,colecciones:{...p.colecciones,prospectos:[{...p.colecciones.prospectos[0],accessToken:'secret'}]}}));
});
test('cohorte agrega conteos históricos sin atribuirlos a actividad',()=>{
 const p:any={...ps[0],fechaRecepcion:filters.desde,intentosHistoricos:7,contactosEfectivosHistoricos:3};const d:any={prospectos:[p],gestiones:[],citas:[],ventas:[],retroalimentaciones:[]};
 assert.equal(calculateReport(d,{...filters,enfoque:'Cohorte'},['propietario']).total.metrics.contactos,7);assert.equal(calculateReport(d,{...filters,enfoque:'Actividad'},['propietario']).total.metrics.contactos,0);
});
