import * as XLSX from 'xlsx';
import { PERSONAL_DATA_WARNING, REPORT_MEASURES, MONEY_MEASURES, formatDateTimeLA,formatExportDateTimeLA } from '../businessRules';
import type { Measure, ReportResult, ReportFilters, BackupFile } from './types';
export const labels:Record<string,string>={estadoPagoHistorico:'Estado de pago histórico',bonoPagadoHistorico:'Bono pagado histórico',intentosHistoricos:'Contactos históricos',contactosEfectivosHistoricos:'Contactos efectivos históricos',id:'ID',idProspecto:'ID de prospecto',idCita:'ID de cita',idVenta:'ID de venta',idLote:'Lote de carga',fechaRecepcion:'Fecha de recepción',fechaProspeccion:'Fecha de prospección',fechaHora:'Fecha y hora',fechaCita:'Fecha de cita',horaCita:'Hora de cita',fechaCreacion:'Fecha de creación',fechaReporte:'Fecha de venta',nombre:'Nombre',telefono:'Teléfono',propietario:'Propietario',telemarketing:'Telemarketing',tipoProspecto:'Tipo de prospecto',ciudadZona:'Ciudad / zona',origen:'Origen',estado:'Estado',estadoCita:'Estado de cita',temperatura:'Temperatura',montoAprobado:'Monto aprobado',porcentajeBono:'Porcentaje de bono',bonoGenerado:'Bono generado',bonoPagable:'Bono pagable',observacion:'Observación',archivado:'Archivado',creadoPor:'Creado por',creadoEn:'Creado el',modificadoEn:'Modificado el',usuario:'Usuario',fecha:'Fecha',resultado:'Resultado',efectivo:'Contacto efectivo'};
export function readable(records:Record<string,any>[]):Record<string,any>[] {return records.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[labels[k]||k.replace(/([a-z])([A-Z])/g,'$1 $2'),/telefono|teléfono|phone/i.test(k)?String(v??''):v&&typeof v==='object'?JSON.stringify(v):typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v)?formatExportDateTimeLA(v):typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v.split('-').reverse().join('/'):v])));}
export function workbook(sheets:Record<string,Record<string,any>[]>) {const wb=XLSX.utils.book_new();for(const [name,records]of Object.entries(sheets)){const ws=XLSX.utils.json_to_sheet(records);ws['!cols']=Object.keys(records[0]||{}).map(()=>({wch:24}));XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31).replace(/[\[\]:*?/\\]/g,'_'));}return wb;}
export function excelBytes(wb:XLSX.WorkBook):ArrayBuffer{return XLSX.write(wb,{type:'array',bookType:'xlsx'});}
export async function download(blob:Blob,name:string,confirmed=false):Promise<void>{if(!confirmed&&!window.confirm(PERSONAL_DATA_WARNING+'\n\n¿Continuar con la descarga?'))throw new Error('Descarga cancelada.');
  const w=window as any;
  if(w.showSaveFilePicker){const handle=await w.showSaveFilePicker({suggestedName:name});const stream=await handle.createWritable();await stream.write(blob);await stream.close();return;}
  const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
}
export function csvBytes(records:Record<string,any>[]):Blob{const ws=XLSX.utils.json_to_sheet(records.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,typeof v==='string'&&/^[=+@\-\t\r]/.test(v)?"'"+v:v]))));return new Blob(['\uFEFF'+XLSX.utils.sheet_to_csv(ws)],{type:'text/csv;charset=utf-8'});}
export function reportWorkbook(result:ReportResult,filters:ReportFilters,measures:Measure[],user:string){
  const rows=[...result.rows,result.total].map(r=>Object.fromEntries([['Grupo',r.groups.join(' / ')],...measures.map(m=>[REPORT_MEASURES[m],r.metrics[m]])]));
  const detail=[...result.data.prospectos.map(r=>({Tabla:'Prospectos',...r})),...result.data.gestiones.map(r=>({Tabla:'Gestiones',...r})),...result.data.citas.map(r=>({Tabla:'Citas',...r})),...result.data.ventas.map(r=>({Tabla:'Ventas',...r}))];
  const wb=workbook({Resumen:rows,Detalle:readable(detail),Filtros:[{...Object.fromEntries(Object.entries(filters).map(([k,v])=>[k,typeof v==='object'?JSON.stringify(v):v])),Usuario:user,Generado:formatExportDateTimeLA(new Date()),'Zona horaria':'America/Los_Angeles'}]});
  const ws=wb.Sheets.Resumen;for(let row=1;row<=rows.length;row++)measures.forEach((m,col)=>{const c=ws[XLSX.utils.encode_cell({r:row,c:col+1})];if(c)c.z=m.startsWith('pct')?'0.0%':MONEY_MEASURES.includes(m)?'"$"#,##0.00':'#,##0';});return wb;
}
export function backupWorkbook(file:BackupFile){const sheets:Record<string,Record<string,any>[]>= {Resumen:Object.entries(file.collections).map(([Colección,r])=>({Colección,Registros:r.length,Fecha:formatExportDateTimeLA(file.fecha),Usuario:file.usuario,'Hash SHA-256':file.hash,'Lectura iniciada':file.lecturaInicio,'Lectura finalizada':file.lecturaFin}))};for(const [name,rs]of Object.entries(file.collections))sheets[name]=readable(rs.map(r=>({'ID del documento':r.id,...r.data})));return workbook(sheets);}
export function printRecords(title:string,records:Record<string,any>[]){if(!window.confirm(PERSONAL_DATA_WARNING+'\n\n¿Abrir impresión / PDF?'))return;const win=window.open('','_blank');if(!win)throw new Error('Permite ventanas emergentes para imprimir.');const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const keys=[...new Set(records.flatMap(r=>Object.keys(r)))];win.document.write(`<html lang="es"><head><title>${esc(title)}</title><style>body{font:11px Arial;color:#0D2240}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:5px;word-break:break-word}thead{display:table-header-group}@page{size:landscape}h1{font-size:20px}</style></head><body><h1>${esc(title)}</h1><p>${esc(formatDateTimeLA(new Date()))} · America/Los_Angeles</p><p>${esc(PERSONAL_DATA_WARNING)}</p><table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${records.map(r=>`<tr>${keys.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`);win.document.close();win.focus();win.print();}
