import {applyRestore} from './restoreEngine';
import { fileJob } from './fileJobs';
import { collection,doc,getDocs,getDocsFromServer,getDoc,getCountFromServer,query,orderBy,documentId,startAfter,limit,where,addDoc,setDoc,runTransaction,writeBatch } from 'firebase/firestore';
import { db,auth } from '../firebase';
import { BACKUP_COLLECTIONS,ADMIN_EMAIL,canonicalBackupRecord } from '../businessRules';
import { encodeRecord,decodeRecord,backupHash,buildRestorePlan } from './backupCodec';
import type { BackupRecord,BackupFile,Progress } from './types';
export const yieldUI=()=>new Promise<void>(resolve=>setTimeout(resolve,0));
export function requireAdmin(){if(!auth.currentUser?.emailVerified||auth.currentUser.email?.toLowerCase()!==ADMIN_EMAIL)throw new Error('Solo el administrador puede realizar esta operación.');}
export async function audit(action:string,details:Record<string,any>={}) {if(!auth.currentUser)throw new Error('Sesión requerida.');await addDoc(collection(db,'auditoria'),{accion:action,usuario:auth.currentUser.email,fecha:new Date().toISOString(),...details});}
export async function registeredCollections():Promise<string[]>{requireAdmin();const snap=await getDoc(doc(db,'settings','backupRegistry'));const extra=snap.data()?.collections||[];if(!Array.isArray(extra)||extra.some((s:any)=>typeof s!=='string'||!/^\w+$/.test(s)||/auth|token|secret/i.test(s)))throw new Error('Registro de colecciones inválido.');return [...new Set([...BACKUP_COLLECTIONS,...extra])] as string[];}
export async function counts(names:string[]){requireAdmin();const result:Record<string,number>={};for(const name of names){result[name]=(await getCountFromServer(collection(db,name))).data().count;await yieldUI();}return result;}
export async function readPaged(name:string,signal:AbortSignal,progress:(p:Progress)=>void,total=0,constraints:any[]=[]):Promise<BackupRecord[]>{const result:BackupRecord[]=[];let cursor:any;while(true){signal.throwIfAborted();const q=query(collection(db,name),...constraints,orderBy(documentId()),...(cursor?[startAfter(cursor)]:[]),limit(500));const snap=await getDocsFromServer(q);signal.throwIfAborted();for(const r of snap.docs)result.push(encodeRecord(r.id,r.data()));progress({message:`Leyendo ${name}... ${result.length.toLocaleString('es')} de ${total.toLocaleString('es')}`,done:result.length,total});if(snap.size<500)break;cursor=snap.docs.at(-1);await yieldUI();}return result;}
// La lectura reanudable guarda páginas por separado en IndexedDB, nunca en Firestore ni Storage.
async function checkpointDB(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open('crm-backup-checkpoint-v1',1);req.onupgradeneeded=()=>{req.result.createObjectStore('pages');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function checkpoint(key:string,value?:any,remove=false):Promise<any>{const db=await checkpointDB();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('pages',value===undefined&&!remove?'readonly':'readwrite');const s=tx.objectStore('pages');let result:any;const req=remove?s.delete(key):value===undefined?s.get(key):s.put(value,key);req.onsuccess=()=>{result=req.result;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
export async function discardCheckpoint(){requireAdmin();const owner=auth.currentUser!.uid;const meta=await checkpoint(owner);if(meta){for(const name of meta.names)for(let i=0;i<(meta.pageCounts?.[name]||0);i++)await checkpoint(`${owner}/${name}/${i}`,undefined,true);await checkpoint(owner,undefined,true);}}
export async function readBackup(signal:AbortSignal,progress:(p:Progress)=>void,resume=false):Promise<BackupFile>{requireAdmin();const owner=auth.currentUser!.uid;let meta=resume?await checkpoint(owner):null;if(!meta){await discardCheckpoint();const names=await registeredCollections();meta={names,counts:await counts(names),pageCounts:{},cursors:{},finished:[],fecha:new Date().toISOString()};await checkpoint(owner,meta);}
  const collections:Record<string,BackupRecord[]>={};
  for(const name of meta.names){collections[name]=[];for(let i=0;i<(meta.pageCounts[name]||0);i++){const page=await checkpoint(`${owner}/${name}/${i}`);if(!page)throw new Error('Punto de reanudación incompleto. Inicia un respaldo nuevo.');collections[name].push(...page);await yieldUI();}
    if(meta.finished.includes(name))continue;
    while(true){signal.throwIfAborted();const snap=await getDocsFromServer(query(collection(db,name),orderBy(documentId()),...(meta.cursors[name]?[startAfter(meta.cursors[name])]:[]),limit(500)));signal.throwIfAborted();const page=snap.docs.map(r=>encodeRecord(r.id,r.data()));const index=meta.pageCounts[name]||0;await checkpoint(`${owner}/${name}/${index}`,page);collections[name].push(...page);meta.pageCounts[name]=index+1;if(snap.size)meta.cursors[name]=snap.docs.at(-1)!.id;if(snap.size<500)meta.finished.push(name);await checkpoint(owner,meta);progress({message:`Leyendo ${name}... ${collections[name].length.toLocaleString('es')} de ${meta.counts[name].toLocaleString('es')}`,done:collections[name].length,total:meta.counts[name]});await yieldUI();if(snap.size<500)break;}
  }
  const file:BackupFile={app:'CRM LLAMADAS',version:1,fecha:new Date().toISOString(),usuario:auth.currentUser!.email!,collections,lecturaInicio:meta.fecha,lecturaFin:new Date().toISOString()};file.hash=await fileJob<string>({job:'hash',file},signal);return file;
}
export async function registerBackup(file:BackupFile,size:number,tipo='completo'){requireAdmin();await addDoc(collection(db,'respaldos'),{fecha:file.fecha,usuario:file.usuario,tipo,conteos:Object.fromEntries(Object.entries(file.collections).map(([k,v])=>[k,v.length])),tamano:size,hash:file.hash,lecturaInicio:file.lecturaInicio||file.fecha,lecturaFin:file.lecturaFin||file.fecha});await audit('RESPALDO',{tipo,hash:file.hash,tamano:size});}
export async function currentFor(file:BackupFile,signal:AbortSignal,progress:(p:Progress)=>void){requireAdmin();const result:Record<string,BackupRecord[]>={};for(const name of Object.keys(file.collections))result[name]=await readPaged(name,signal,progress);return result;}
export async function restore(file:BackupFile,current:Record<string,BackupRecord[]>,selected:string[],mode:'missing'|'replace',remove:boolean,includeUsers:boolean,signal:AbortSignal,progress:(p:Progress)=>void,filename:string){requireAdmin();return applyRestore(db,auth.currentUser!.email!,file,current,selected,mode,remove,includeUsers,signal,progress,filename);}
export async function updateInChunks(name:string,rows:{id:string;data:Record<string,any>}[],action:string,signal?:AbortSignal,details:Record<string,any>={}){requireAdmin();let applied=0;const log=await addDoc(collection(db,'auditoria'),{accion:action,fecha:new Date().toISOString(),usuario:auth.currentUser!.email,total:rows.length,aplicados:0,estado:'En curso',detalles:details});for(let i=0;i<rows.length;i+=399){if(signal?.aborted)break;const batch=writeBatch(db);const group=rows.slice(i,i+399);group.forEach(r=>batch.update(doc(db,name,r.id),r.data));batch.update(log,{aplicados:applied+group.length});try{await batch.commit();}catch(e){await setDoc(log,{estado:'Detenida',error:String(e)},{merge:true});throw new Error(`Se aplicaron ${applied} registros; lote ${Math.floor(i/399)+1} falló: ${String(e)}`);}applied+=group.length;await yieldUI();}await setDoc(log,{estado:applied===rows.length?'Completada':'Cancelada',aplicados:applied},{merge:true});return applied;}
