import React,{useState,useMemo} from 'react';
export const Button=({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>)=><button {...props} className={'crm78-button '+(props.className||'')}>{children}</button>;
export function DataTable({rows,totals,onCell,max=50}:{rows:Record<string,any>[];totals?:Record<string,any>;onCell?:(row:Record<string,any>,key:string)=>void;max?:number}){
 const [search,setSearch]=useState(''),[sort,setSort]=useState(''),[desc,setDesc]=useState(false),[page,setPage]=useState(0);
 const keys=Object.keys(rows[0]||totals||{}).filter(k=>!k.startsWith('_'));
 const visible=useMemo(()=>rows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>{if(!sort)return 0;const n=typeof a[sort]==='number'?a[sort]-b[sort]:String(a[sort]??'').localeCompare(String(b[sort]??''),'es',{numeric:true});return desc?-n:n;}),[rows,search,sort,desc]);
 const last=Math.max(0,Math.ceil(visible.length/max)-1),current=Math.min(page,last);
 const format=(key:string,v:any)=>typeof v==='number'?key.startsWith('%')?(v*100).toFixed(1)+'%':/Monto|Bono|bono/.test(key)?v.toLocaleString('es-US',{style:'currency',currency:'USD'}):v.toLocaleString('es'):typeof v==='object'?JSON.stringify(v):String(v??'');
 return <div className="crm78-table"><input aria-label="Buscar en la tabla" placeholder="Buscar dentro de la tabla" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><div className="crm78-scroll"><table><thead><tr>{keys.map(k=><th key={k}><button onClick={()=>{setDesc(sort===k?!desc:false);setSort(k);}}>{k} {sort===k?(desc?'↓':'↑'):''}</button></th>)}</tr></thead><tbody>{visible.slice(current*max,(current+1)*max).map((r,i)=><tr key={r._key||r.ID||i}>{keys.map(k=><td key={k}>{onCell?<button className="crm78-cell" onClick={()=>onCell(r,k)}>{format(k,r[k])}</button>:format(k,r[k])}</td>)}</tr>)}</tbody>{totals&&<tfoot><tr>{keys.map(k=><td key={k}>{onCell?<button className="crm78-cell" onClick={()=>onCell(totals,k)}>{format(k,totals[k])}</button>:format(k,totals[k])}</td>)}</tr></tfoot>}</table></div>{!visible.length&&<p className="crm78-empty">No hay registros que coincidan con estos filtros.</p>}<div className="crm78-toolbar"><span>{visible.length.toLocaleString('es')} filas · página {current+1} de {last+1}</span><Button disabled={current===0} onClick={()=>setPage(current-1)}>Anterior</Button><Button disabled={current===last} onClick={()=>setPage(current+1)}>Siguiente</Button></div></div>;
}
export function MultiSelect({label,options,value,onChange}:{label:string;options:string[];value:string[];onChange:(v:string[])=>void}){const [search,setSearch]=useState('');return <details className="crm78-multi"><summary>{label}{value.length?` (${value.length})`:''}</summary><input aria-label={'Buscar '+label} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar…"/><div>{options.filter(o=>o.toLowerCase().includes(search.toLowerCase())).map(o=><label key={o}><input type="checkbox" checked={value.includes(o)} onChange={e=>onChange(e.target.checked?[...value,o]:value.filter(v=>v!==o))}/>{o||'Sin dato'}</label>)}</div></details>;}
export function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="crm78-overlay"><section role="dialog" aria-modal="true" aria-label={title} className="crm78-modal"><div className="crm78-toolbar"><h2>{title}</h2><Button onClick={onClose}>Cerrar</Button></div>{children}</section></div>;}
