import React,{useMemo,useState,useEffect} from 'react';
import { collection,getDocs,query,where,orderBy,limit } from 'firebase/firestore';
import { db } from '../firebase';
import { useCRM } from '../context/CRMContext';
import { useAuth } from '../context/AuthContext';
import { normalizePhone,normalizeOwner,getDateInLA,formatDateTimeLA,getTodayInLA } from '../businessRules';
import { Button,DataTable,Modal } from '../stage78/ui';
import { readable,workbook,excelBytes,download,printRecords } from '../stage78/export';
import { audit } from '../stage78/service';
import type { Prospecto } from '../types';
export function ConsultaGlobalView({onOpenProspecto}:{onOpenProspecto:(p:Prospecto)=>void}){
 const crm=useCRM(),{isSupervisor}=useAuth();const [text,setText]=useState(''),[search,setSearch]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[agent,setAgent]=useState(''),[state,setState]=useState(''),[opened,setOpened]=useState<Prospecto|null>(null),[assignments,setAssignments]=useState<any[]>([]),[error,setError]=useState('');
 useEffect(()=>{const t=setTimeout(()=>setSearch(text),250);return()=>clearTimeout(t);},[text]);
 const index=useMemo(()=>new Map(crm.prospectos.map(p=>[p.id,p])),[crm.prospectos]);
 const results=useMemo(()=>{if(!search.trim())return {prospectos:[],citas:[],ventas:[]};const term=normalizeOwner(search),phone=/^[\d\s()+.\-]+$/.test(search)?normalizePhone(search):'';
 const matches=(p:Prospecto)=>[p.id,p.nombre,p.propietario].some(v=>normalizeOwner(v).includes(term))||!!phone&&normalizePhone(p.telefono).includes(phone);
 const filter=(p:Prospecto,date:string)=>{const d=getDateInLA(date);return (!from||d>=from)&&(!to||!!d&&d<=to)&&(!agent||p.telemarketing===agent)&&(!state||p.estado===state);};
 return {prospectos:crm.prospectos.filter(p=>matches(p)&&filter(p,p.fechaRecepcion)),citas:crm.citas.filter(c=>{const p=index.get(c.idProspecto);return p&&filter(p,c.fechaCita)&&(matches(p)||normalizeOwner(c.id).includes(term));}),ventas:crm.ventas.filter(v=>{const p=index.get(v.idProspecto);return p&&filter(p,v.fechaReporte)&&(matches(p)||normalizeOwner(v.id).includes(term));})};},[search,from,to,agent,state,crm.prospectos,crm.citas,crm.ventas,index]);
 useEffect(()=>{setAssignments([]);if(!opened||!isSupervisor)return;let alive=true;getDocs(query(collection(db,'logAsignaciones'),where('idProspecto','==',opened.id))).then(s=>{if(alive)setAssignments(s.docs.map(d=>({id:d.id,...d.data()})));}).catch(e=>{if(alive)setError('No se pudo consultar el historial de asignación: '+e.message);});return()=>{alive=false;};},[opened?.id,isSupervisor]);
 const dossier=useMemo(()=>{if(!opened)return null;const p=index.get(opened.id)||opened;const gs=crm.gestiones.filter(g=>g.idProspecto===p.id),cs=crm.citas.filter(c=>c.idProspecto===p.id),rs=crm.retroalimentaciones.filter(r=>r.idProspecto===p.id),vs=crm.ventas.filter(v=>v.idProspecto===p.id),vIds=new Set(vs.map(v=>v.id));const lots=crm.logsCargas.filter(l=>l.idLote===p.idLote),logs=crm.logsVentas.filter(l=>vIds.has(l.idVenta));
 const timeline=[{Tipo:'Recepción del prospecto',Fecha:p.creadoEn||p.fechaRecepcion,ID:p.id,Detalle:JSON.stringify({propietario:p.propietario,origen:p.origen,lote:p.idLote||''})},...gs.map(g=>({Tipo:'Gestión',Fecha:g.fechaHora,ID:g.id,Detalle:`${g.resultado} · ${g.telemarketing} · ${g.observacion}`})),...cs.map(c=>({Tipo:'Cita',Fecha:c.ultimaActualizacion||c.fechaCreacion,ID:c.id,Detalle:`${c.fechaCita} ${c.horaCita} · ${c.estadoCita} · ${c.telemarketing}`})),...rs.map(r=>({Tipo:'Resultado de cita',Fecha:r.creadoEn||r.fecha,ID:r.id,Detalle:`${r.resultado} · ${r.observacion}`})),...vs.map(v=>({Tipo:'Venta y bono',Fecha:v.ultimaActualizacion||v.fechaReporte,ID:v.id,Detalle:`${v.estado} · Monto: ${v.montoAprobado??'Pendiente'} · Bono generado: ${v.bonoGenerado??0} · Pagable: ${v.bonoPagable??0}`})),...logs.map(l=>({Tipo:'Cambio de venta',Fecha:l.fechaHora,ID:l.id,Detalle:JSON.stringify(l)})),...lots.map(l=>({Tipo:'Carga masiva',Fecha:l.fechaHora,ID:l.idLote,Detalle:`${l.nombreArchivo} · ${l.usuario}`})),...assignments.map(l=>({Tipo:'Cambio de asignación',Fecha:l.fecha,ID:l.id,Detalle:`${l.anterior} → ${l.nueva} · ${l.usuario}`}))].sort((a,b)=>b.Fecha.localeCompare(a.Fecha));return {p,timeline,gs,cs,rs,vs,lots,logs};},[opened,index,crm.gestiones,crm.citas,crm.retroalimentaciones,crm.ventas,crm.logsCargas,crm.logsVentas,assignments]);
 const exportDossier=async()=>{if(!dossier)return;try{await audit('EXPORTAR_EXPEDIENTE',{idProspecto:dossier.p.id});await download(new Blob([excelBytes(workbook({Prospecto:readable([dossier.p]),'Línea de tiempo':dossier.timeline,Gestiones:readable(dossier.gs),Citas:readable(dossier.cs),Resultados:readable(dossier.rs),Ventas:readable(dossier.vs),Cargas:readable(dossier.lots),'Cambios de venta':readable(dossier.logs),Asignaciones:readable(assignments)}))]),`expediente_${dossier.p.id}_${getTodayInLA()}.xlsx`);}catch(e){setError(String(e));}};
 if(!isSupervisor)return <p>Solo el administrador puede acceder al Buscador global.</p>;
 return <section className="crm78"><div className="crm78-card"><h2>Buscador global</h2><p>Encuentra un prospecto y consulta su expediente completo: llamadas, citas, resultados, ventas y cambios de asignación. Busca por teléfono, nombre, ID o propietario.</p><input style={{width:'100%',margin:'12px 0'}} aria-label="Búsqueda global" value={text} onChange={e=>setText(e.target.value)} placeholder="Teléfono, nombre, ID o propietario…"/><div className="crm78-toolbar"><label>Desde <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><select aria-label="Telemarketing" value={agent} onChange={e=>setAgent(e.target.value)}><option value="">Todas las telemarketing</option>{crm.settings.telemarketingAgents.map(a=><option key={a.id}>{a.name}</option>)}</select><select aria-label="Estado" value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option>{crm.settings.estadosDisponibles.map(s=><option key={s}>{s}</option>)}</select></div><p>Los filtros de fecha usan recepción para prospectos, fecha de cita para citas y fecha de reporte para ventas.</p></div>
 {error&&<p className="crm78-error">{error}</p>}{crm.loading?<div className="crm78-skeleton"/>:!search.trim()?<p className="crm78-empty">Escribe un nombre, teléfono o propietario para buscar. Selecciona un resultado para abrir su historial completo.</p>:<>{(['prospectos','citas','ventas'] as const).map(name=><div className="crm78-card" key={name}><h3>{name==='prospectos'?'Prospectos':name==='citas'?'Citas':'Ventas'} · {results[name].length}</h3><DataTable rows={readable(results[name])} onCell={r=>{const p=index.get(r['ID de prospecto']||r.ID);if(p)setOpened(p);}}/></div>)}</>}
 {dossier&&<Modal title={`Expediente · ${dossier.p.nombre}`} onClose={()=>setOpened(null)}><div className="crm78-toolbar"><Button onClick={()=>onOpenProspecto(dossier.p)}>Abrir prospecto</Button><Button onClick={exportDossier}>Exportar expediente a Excel</Button><Button onClick={async()=>{try{await audit('IMPRIMIR_EXPEDIENTE',{idProspecto:dossier.p.id});printRecords(`Expediente ${dossier.p.nombre}`,[{Tipo:'Datos del prospecto',Fecha:dossier.p.creadoEn,ID:dossier.p.id,Detalle:JSON.stringify(dossier.p)},...dossier.timeline]);}catch(e){setError(String(e));}}}>Imprimir / PDF</Button></div><DataTable rows={readable([dossier.p])}/><h3>Línea de tiempo · más reciente primero</h3><div className="crm78-timeline">{dossier.timeline.map((event,i)=><article key={event.ID+i}><strong>{event.Tipo}</strong><p>{formatDateTimeLA(event.Fecha)} · {event.ID}</p><p>{event.Detalle}</p></article>)}</div>{!assignments.length&&<p>No hay cambios de asignación registrados. Los cambios anteriores a esta actualización no pueden reconstruirse.</p>}</Modal>}
 </section>;
}
