import { fileJob } from '../stage78/fileJobs';
import React,{useState,useMemo,useEffect,useRef} from 'react';
import { BarChart,Bar,LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid } from 'recharts';
import { collection,onSnapshot,query,where,addDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { useCRM } from '../context/CRMContext';
import { useAuth } from '../context/AuthContext';
import { REPORT_DIMENSIONS,REPORT_MEASURES,MONEY_MEASURES,getDateRangePreset,getTodayInLA,normalizeOwner,calculateReport,reportRatios,emptyReportMetrics } from '../businessRules';
import type { Dimension,Measure,ReportFilters,ReportResult,ReportRow } from '../stage78/types';
import type { Prospecto } from '../types';
import { Button,DataTable,MultiSelect,Modal } from '../stage78/ui';
import { download,excelBytes,reportWorkbook,readable,csvBytes,workbook,printRecords } from '../stage78/export';
import { audit,yieldUI } from '../stage78/service';
const PRESETS:{name:string;dims:Dimension[];money?:boolean}[]=[{name:'Por propietario',dims:['propietario']},{name:'Por fecha',dims:['fecha']},{name:'Por telemarketing',dims:['telemarketing']},{name:'Por tipo',dims:['tipoProspecto']},{name:'Por origen',dims:['origen']},{name:'Por ciudad / zona',dims:['ciudadZona']},{name:'Por estado',dims:['estado']},{name:'Por temperatura',dims:['temperatura']},{name:'Citas',dims:['fecha','estadoCita']},{name:'Ventas y bonos',dims:['fecha'],money:true},{name:'Embudo',dims:[]},{name:'Cruce',dims:['propietario','telemarketing']},{name:'Constructor',dims:['propietario']}];
const defaults=():ReportFilters=>({...getDateRangePreset('mes'),base:'fechaRecepcion',enfoque:'Actividad',periodo:'día',values:{}});
export function ReportesView({onOpenProspecto}:{onOpenProspecto:(p:Prospecto)=>void}) {
 const crm=useCRM(),{user,isAdmin,isSupervisor,telemarketingAgent}=useAuth();
 const [draft,setDraft]=useState(defaults),[filters,setFilters]=useState(defaults),[tab,setTab]=useState('Por propietario'),[dims,setDims]=useState<Dimension[]>(['propietario']),[measures,setMeasures]=useState<Measure[]>(Object.keys(REPORT_MEASURES).filter(m=>m!=='pendientes') as Measure[]),[result,setResult]=useState<ReportResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState<{title:string;records:any[]}|null>(null),[saved,setSaved]=useState<any[]>([]),[saveName,setSaveName]=useState(''),[share,setShare]=useState(false),[exporting,setExporting]=useState(false),[matrixMeasure,setMatrixMeasure]=useState<Measure>('prospectos');
 const seq=useRef(0),worker=useRef<Worker|null>(null);
 const data=useMemo(()=>{const ps=isSupervisor?crm.prospectos:crm.prospectos.filter(p=>!!telemarketingAgent&&p.telemarketing===telemarketingAgent);const ids=new Set(ps.map(p=>p.id));return {prospectos:ps,gestiones:crm.gestiones.filter(r=>ids.has(r.idProspecto)),citas:crm.citas.filter(r=>ids.has(r.idProspecto)),ventas:crm.ventas.filter(r=>ids.has(r.idProspecto)).map(v=>isSupervisor?v:({...v,montoAprobado:null,porcentajeBono:null,bonoGenerado:null,bonoPagable:null})),retroalimentaciones:crm.retroalimentaciones.filter(r=>ids.has(r.idProspecto))};},[crm.prospectos,crm.gestiones,crm.citas,crm.ventas,crm.retroalimentaciones,isSupervisor,telemarketingAgent]);
 const availableMeasures=(Object.keys(REPORT_MEASURES) as Measure[]).filter(m=>isSupervisor||!MONEY_MEASURES.includes(m));const columns=measures.filter(m=>availableMeasures.includes(m));
 useEffect(()=>{worker.current=new Worker(new URL('../stage78/report.worker.ts',import.meta.url),{type:'module'});worker.current.onmessage=({data:msg})=>{if(msg.id!==seq.current)return;if(msg.error)setError(msg.error);else setResult(msg.result);setBusy(false);};worker.current.onerror=()=>{setError('No se pudo calcular el reporte. Recarga la aplicación.');setBusy(false);};return()=>worker.current?.terminate();},[]);
 useEffect(()=>{setBusy(true);setError('');const id=++seq.current;worker.current?.postMessage({id,data,filters,dimensions:dims,scope:isSupervisor?undefined:telemarketingAgent||''});},[data,filters,dims,isSupervisor,telemarketingAgent]);
 useEffect(()=>{if(!user)return;const qs=isSupervisor?[query(collection(db,'reportesGuardados'))]:[query(collection(db,'reportesGuardados'),where('usuario','==',user.email)),query(collection(db,'reportesGuardados'),where('compartido','==',true))];const lists:any[][]=qs.map(()=>[]);const subs=qs.map((q,i)=>onSnapshot(q,s=>{lists[i]=s.docs.map(d=>({id:d.id,...d.data()}));setSaved([...new Map(lists.flat().map(r=>[r.id,r])).values()]);},e=>setError('No se pudieron cargar reportes guardados: '+e.message)));return()=>subs.forEach(s=>s());},[user,isSupervisor]);
 const options=useMemo(()=>Object.fromEntries(Object.keys(REPORT_DIMENSIONS).filter(k=>!['fecha','estadoCita'].includes(k)).map(k=>[k,[...new Set(data.prospectos.map(p=>String((p as any)[k]||'')))].sort()])),[data.prospectos]);
 const rows=result?.rows.map(r=>({_key:r.key,Grupo:r.groups.join(' / '),...Object.fromEntries(columns.map(m=>[REPORT_MEASURES[m],r.metrics[m]]))}))||[];
 const total=result?{_key:'TOTAL',Grupo:'TOTAL',...Object.fromEntries(columns.map(m=>[REPORT_MEASURES[m],result.total.metrics[m]]))}:undefined;
 const selectTab=(name:string)=>{setTab(name);const preset=PRESETS.find(p=>p.name===name)!;setDims(preset.dims);if(name==='Citas')setMeasures(['citas','realizadas','pendientes']);else if(name==='Ventas y bonos')setMeasures(['ventas','monto','bonoGenerado','bonoPagable']);else setMeasures(availableMeasures.filter(m=>m!=='pendientes'));};
 const showDetail=(r:any,label:string)=>{if(!result)return;const row=r._key==='TOTAL'?result.total:result.rows.find(x=>x.key===r._key);if(!row)return;const m=(Object.entries(REPORT_MEASURES).find(([k,v])=>v===label)?.[0]||'prospectos') as Measure;let records:any[]=[];const gIds=new Set(row.ids.gestiones),cIds=new Set(row.ids.citas),vIds=new Set(row.ids.ventas),pIds=new Set(row.ids.prospectos);const gs=result.data.gestiones.filter(g=>gIds.has(g.id));const cs=result.data.citas.filter(c=>cIds.has(c.id));const vs=result.data.ventas.filter(v=>vIds.has(v.id));const related=new Set(gs.map(g=>g.idProspecto));
 if(['contactos','efectivos','pctEfectividad'].includes(m))records=m==='efectivos'?gs.filter(g=>g.efectivo==='Sí'):gs;
 else if(['citas','realizadas','pendientes','pctCita'].includes(m))records=m==='realizadas'?cs.filter(c=>c.estadoCita==='Realizada'):m==='pendientes'?cs.filter(c=>c.estadoCita!=='Cancelada'&&!result.data.retroalimentaciones.some(r=>r.idCita===c.id)):cs;
 else if(['ventas','monto','bonoGenerado','bonoPagable','pctVenta'].includes(m))records=m==='monto'?vs.filter(v=>v.estado==='Aprobada'):vs;
 else records=result.data.prospectos.filter(p=>m==='contactados'?related.has(p.id):pIds.has(p.id)).filter(p=>m==='asignados'?!!p.telemarketing&&p.telemarketing!=='SIN ASIGNAR':m==='sinAsignar'?!p.telemarketing||p.telemarketing==='SIN ASIGNAR':true);
 if(m==='pctContactados')records=[...result.data.prospectos.filter(p=>pIds.has(p.id)).map(p=>({Componente:'Denominador: prospectos',...p})),...result.data.prospectos.filter(p=>related.has(p.id)).map(p=>({Componente:'Numerador: contactados',...p}))];
 if(m==='pctEfectividad')records=gs.map(g=>({Componente:g.efectivo==='Sí'?'Efectivo (numerador y denominador)':'Contacto (denominador)',...g}));
 if(m==='pctCita')records=[...gs.filter(g=>g.efectivo==='Sí').map(g=>({Componente:'Denominador: contactos efectivos',...g})),...cs.map(c=>({Componente:'Numerador: citas',...c}))];
 if(m==='pctVenta')records=[...cs.map(c=>({Componente:'Denominador: citas',...c})),...vs.map(v=>({Componente:'Numerador: ventas no canceladas',...v}))];
 setDetail({title:`${label} · ${r.Grupo}`,records});};
 const exportOne=async(csv=false)=>{if(!result)return;setExporting(true);try{await audit('EXPORTAR_REPORTE',{nombre:tab,filtros:filters,formato:csv?'CSV':'Excel'});const filename=`reporte_${tab.replace(/\W/g,'_')}_${filters.desde}_${filters.hasta}`;await download(csv?csvBytes(rows.map(({_key,...r})=>r)):await fileJob({job:'report',result,filters,measures:columns,user:user?.email||'',matrix:pivot?{rows:pivot.rows,total:pivot.total,measure:matrixMeasure}:undefined}),filename+(csv?'.csv':'.xlsx'));}catch(e){setError(String(e));}finally{setExporting(false);}};
 const exportAll=async()=>{setExporting(true);try{const sheets:Record<string,any[]>={};for(const p of PRESETS.filter(p=>p.name!=='Constructor')){const r=calculateReport(data,filters,p.dims);sheets[p.name]=[...r.rows,r.total].map(row=>({Grupo:row.groups.join(' / '),...Object.fromEntries(availableMeasures.map(m=>[REPORT_MEASURES[m],row.metrics[m]]))}));await yieldUI();}sheets.Filtros=[{...filters,values:JSON.stringify(filters.values),Usuario:user?.email,Generado:new Date().toISOString()}];await audit('EXPORTAR_TODOS_REPORTES',{filtros:filters});await download(await fileJob({job:'sheets',sheets,formatMetrics:true}),`reportes_todos_${filters.desde}_${filters.hasta}.xlsx`);}catch(e){setError(String(e));}finally{setExporting(false);}};
 const save=async()=>{if(!saveName.trim())return;try{await addDoc(collection(db,'reportesGuardados'),{nombre:saveName.trim(),usuario:user?.email,fecha:new Date().toISOString(),compartido:isAdmin&&share,filters,dims,measures:columns,tab});setSaveName('');}catch(e){setError(String(e));}};
 const gestionProspectMap=useMemo(()=>new Map(result?.data.gestiones.map(g=>[g.id,g.idProspecto])||[]),[result]);
 const pivot=useMemo(()=>{if(!result||dims.length!==2)return null;const categories=[...new Set(result.rows.map(r=>r.groups[1]))];const groups=new Map<string,ReportRow[]>();for(const r of result.rows){const list=groups.get(r.groups[0])||[];list.push(r);groups.set(r.groups[0],list);}const measure=availableMeasures.includes(matrixMeasure)?matrixMeasure:'prospectos';const aggregate=(rs:ReportRow[])=>{const m=emptyReportMetrics();for(const r of rs)for(const k of Object.keys(m) as Measure[])if(!k.startsWith('pct'))m[k]+=r.metrics[k];const gestionIds=new Set(rs.flatMap(r=>r.ids.gestiones));m.contactados=new Set(result.data.gestiones.filter(g=>gestionIds.has(g.id)).map(g=>g.idProspecto)).size;return reportRatios(m)[measure];};return {rows:[...groups].map(([g,rs])=>({_key:g,Grupo:g,...Object.fromEntries(categories.map(c=>[c,aggregate(rs.filter(r=>r.groups[1]===c))])),Total:aggregate(rs)})),total:{Grupo:'TOTAL',...Object.fromEntries(categories.map(c=>[c,aggregate(result.rows.filter(r=>r.groups[1]===c))])),Total:result.total.metrics[measure]}};},[result,dims,columns.join(','),matrixMeasure]);
 return <section className="crm78"><h2>Reportes</h2><p>Datos atribuidos al prospecto · America/Los_Angeles · {isSupervisor?'Todos los datos':'Solo tus prospectos asignados'}</p>
 <details open className="crm78-card crm78-filterpanel"><summary>Filtros combinables</summary><div className="crm78-toolbar">{[['Hoy','hoy'],['Ayer','ayer'],['Esta semana','semana'],['Este mes','mes'],['Mes anterior','mes_anterior'],['Últimos 30 días','ultimos_30'],['Este año','año']].map(([label,p])=><Button key={p} onClick={()=>setDraft({...draft,...(p==='año'?{desde:getTodayInLA().slice(0,4)+'-01-01',hasta:getTodayInLA()}:getDateRangePreset(p as any))})}>{label}</Button>)}</div>
 <p className="crm78-note">Los conteos históricos importados sin llamadas individuales se incluyen en Cohorte; no se asignan a períodos de Actividad. Los prospectos sin fecha de recepción requieren revisión para reportes de cohorte.</p><div className="crm78-grid"><label>Desde<input type="date" value={draft.desde} onChange={e=>setDraft({...draft,desde:e.target.value})}/></label><label>Hasta<input type="date" value={draft.hasta} onChange={e=>setDraft({...draft,hasta:e.target.value})}/></label><label>Fecha base<select value={draft.base} onChange={e=>setDraft({...draft,base:e.target.value as any})}>{Object.entries({fechaRecepcion:'Recepción del prospecto',fechaProspeccion:'Prospección',fechaHora:'Gestión (llamada)',fechaCreacion:'Creación de la cita',fechaCita:'Fecha de cita'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Enfoque <span title="Actividad: eventos dentro del período. Cohorte: prospectos recibidos en el período y todo su historial posterior.">ⓘ</span><select value={draft.enfoque} onChange={e=>setDraft({...draft,enfoque:e.target.value as any})}><option>Actividad</option><option>Cohorte</option></select></label>{Object.entries(options).map(([k,vs])=><MultiSelect key={k} label={REPORT_DIMENSIONS[k as Dimension]} options={vs as string[]} value={draft.values[k as Dimension]||[]} onChange={v=>setDraft({...draft,values:{...draft.values,[k]:v}})}/>)}</div>
 <div className="crm78-toolbar"><Button className="gold" onClick={()=>{if(!draft.desde||!draft.hasta||draft.desde>draft.hasta){setError('Revisa el rango de fechas.');return;}setFilters(structuredClone(draft));}}>Aplicar</Button><Button onClick={()=>{setDraft(defaults());setFilters(defaults());}}>Limpiar filtros</Button><input aria-label="Nombre del reporte" placeholder="Nombre para guardar este reporte" value={saveName} onChange={e=>setSaveName(e.target.value)}/>{isAdmin&&<label><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/>Compartir con todos</label>}<Button disabled={!saveName.trim()} onClick={save}>Guardar este reporte</Button><select aria-label="Abrir reporte guardado" value="" onChange={e=>{const r=saved.find(s=>s.id===e.target.value);if(!r)return;setDraft(r.filters);setFilters(r.filters);setDims(r.dims);setMeasures(r.measures);setTab(r.tab);}}><option value="">Abrir reporte guardado…</option>{saved.map(r=><option key={r.id} value={r.id}>{r.nombre}{r.compartido?' · Compartido':''}</option>)}</select></div></details>
 <nav className="crm78-tabs">{PRESETS.filter(p=>!p.money||isSupervisor).map(p=><Button key={p.name} className={tab===p.name?'gold':''} onClick={()=>selectTab(p.name)}>{p.name}</Button>)}</nav>
 <div className="crm78-card"><div className="crm78-toolbar"><label>Agrupar fecha <select value={filters.periodo} onChange={e=>{setFilters({...filters,periodo:e.target.value as any});setDraft({...draft,periodo:e.target.value as any});}}><option>día</option><option>semana</option><option>mes</option></select></label>{(tab==='Constructor'||tab==='Cruce'||tab==='Ventas y bonos'||tab==='Citas')&&<><label>Primera dimensión<select value={dims[0]||''} onChange={e=>setDims([e.target.value as Dimension,...dims.slice(1)])}>{Object.entries(REPORT_DIMENSIONS).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Segunda dimensión<select value={dims[1]||''} onChange={e=>setDims(e.target.value?[dims[0],e.target.value as Dimension]:[dims[0]])}><option value="">Ninguna</option>{Object.entries(REPORT_DIMENSIONS).filter(([k])=>k!==dims[0]).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></>}
 <MultiSelect label="Columnas visibles" options={availableMeasures.map(m=>REPORT_MEASURES[m])} value={columns.map(m=>REPORT_MEASURES[m])} onChange={v=>setMeasures(availableMeasures.filter(m=>v.includes(REPORT_MEASURES[m])))}/><Button disabled={busy||exporting} onClick={()=>exportOne()}>Exportar a Excel</Button><Button disabled={busy||exporting} onClick={()=>exportOne(true)}>Exportar a CSV</Button><Button disabled={busy} onClick={async()=>{try{await audit('IMPRIMIR_REPORTE',{nombre:tab});printRecords(tab,[...rows,...(total?[total]:[])].map(({_key,...r})=>r));}catch(e){setError(String(e));}}}>Imprimir / PDF</Button>{isSupervisor&&<Button disabled={exporting} onClick={exportAll}>Exportar todos los reportes</Button>}</div>
 {error&&<p className="crm78-error">{error}</p>}{busy||crm.loading?<div className="crm78-skeleton" aria-label="Calculando reporte"/>:result&&<>
 {tab==='Embudo'?<div className="crm78-funnel">{(['prospectos','contactados','efectivos','citas','ventas'] as Measure[]).map((m,i,ms)=><div key={m} style={{width:`${95-i*12}%`}}>{REPORT_MEASURES[m]}: {result.total.metrics[m]}{i>0&&<p>{(result.total.metrics[ms[i-1]]?100*result.total.metrics[m]/result.total.metrics[ms[i-1]]:0).toFixed(1)}% de paso</p>}</div>)}</div>:<>
 {pivot&&<><label>Medida de la matriz <select value={matrixMeasure} onChange={e=>setMatrixMeasure(e.target.value as Measure)}>{availableMeasures.map(m=><option key={m} value={m}>{REPORT_MEASURES[m]}</option>)}</select></label><p>Matriz · {REPORT_MEASURES[matrixMeasure]}</p><DataTable rows={pivot.rows} totals={pivot.total} onCell={(r,k)=>{const matching=result.rows.filter(x=>(r.Grupo==='TOTAL'||x.groups[0]===r.Grupo)&&(k==='Total'||x.groups[1]===k));let records:any[]=[];if(['contactos','efectivos','pctEfectividad'].includes(matrixMeasure)){const ids=new Set(matching.flatMap(x=>x.ids.gestiones));records=result.data.gestiones.filter(g=>ids.has(g.id)&&(matrixMeasure!=='efectivos'||g.efectivo==='Sí'));}else if(['citas','realizadas','pendientes','pctCita'].includes(matrixMeasure)){const ids=new Set(matching.flatMap(x=>x.ids.citas));const done=new Set(result.data.retroalimentaciones.map(x=>x.idCita));records=result.data.citas.filter(c=>ids.has(c.id)&&(matrixMeasure!=='realizadas'||c.estadoCita==='Realizada')&&(matrixMeasure!=='pendientes'||c.estadoCita!=='Cancelada'&&!done.has(c.id)));}else if(['ventas','monto','bonoGenerado','bonoPagable','pctVenta'].includes(matrixMeasure)){const ids=new Set(matching.flatMap(x=>x.ids.ventas));records=result.data.ventas.filter(v=>ids.has(v.id)&&(matrixMeasure!=='monto'||v.estado==='Aprobada'));}else{const ids=matrixMeasure==='contactados'?new Set(matching.flatMap(x=>x.ids.gestiones).map(id=>gestionProspectMap.get(id)).filter(Boolean)):new Set(matching.flatMap(x=>x.ids.prospectos));records=result.data.prospectos.filter(p=>ids.has(p.id)&&(matrixMeasure!=='asignados'||!!p.telemarketing&&p.telemarketing!=='SIN ASIGNAR')&&(matrixMeasure!=='sinAsignar'||!p.telemarketing||p.telemarketing==='SIN ASIGNAR'));}setDetail({title:`${REPORT_MEASURES[matrixMeasure]} · ${r.Grupo} / ${k}`,records});}}/></>}
 <DataTable rows={rows} totals={total} onCell={showDetail}/>
 {result.rows.length>0&&<div style={{height:300,marginTop:24}}><ResponsiveContainer>{dims[0]==='fecha'?<LineChart data={[...result.rows].sort((a,b)=>a.groups[0].localeCompare(b.groups[0])).map(r=>({name:r.groups.join(' / '),valor:r.metrics[columns[0]||'prospectos']}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line dataKey="valor" stroke="#B8922A"/></LineChart>:<BarChart data={[...result.rows].sort((a,b)=>b.metrics[columns[0]||'prospectos']-a.metrics[columns[0]||'prospectos']).slice(0,10).map(r=>({name:r.groups.join(' / '),valor:r.metrics[columns[0]||'prospectos']}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="valor" fill="#0D2240"/></BarChart>}</ResponsiveContainer></div>}</>}
 </>}</div>
 {detail&&<Modal title={detail.title} onClose={()=>setDetail(null)}><Button onClick={async()=>{try{await audit('EXPORTAR_DETALLE_REPORTE',{reporte:tab});await download(new Blob([excelBytes(workbook({Detalle:readable(detail.records)}))]),`detalle_${filters.desde}_${filters.hasta}.xlsx`);}catch(e){setError(String(e));}}}>Exportar detalle</Button><DataTable rows={readable(detail.records)} onCell={(r)=>{const id=r['ID de prospecto']||r.ID;const p=data.prospectos.find(p=>p.id===id);if(p)onOpenProspecto(p);}}/><p>Pulsa un registro para abrir su prospecto.</p></Modal>}
 </section>;
}
