import { MigracionHistoricaView } from './MigracionHistoricaView';
import { fileJob } from '../stage78/fileJobs';
import React,{useState,useEffect,useRef} from 'react';
import JSZip from 'jszip';
import { collection,query,orderBy,limit,onSnapshot,setDoc,doc,writeBatch,deleteDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { useAuth } from '../context/AuthContext';
import { useCRM } from '../context/CRMContext';
import { BACKUP_COLLECTIONS,PERSONAL_DATA_WARNING,backupAge,compareBackup,inspectCRMIntegrity,formatDateTimeLA,getDateInLA,getTodayInLA } from '../businessRules';
import { validateBackup } from '../stage78/backupCodec';
import { readBackup,registerBackup,registeredCollections,counts,readPaged,currentFor,restore,audit,discardCheckpoint } from '../stage78/service';
import { download,excelBytes,backupWorkbook,csvBytes,readable,workbook } from '../stage78/export';
import { Button,DataTable,Modal } from '../stage78/ui';
import type { BackupFile,BackupRecord,Progress } from '../stage78/types';
import type { Prospecto } from '../types';
const stamp=(d:string)=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(d));const get=(key:string)=>parts.find(p=>p.type===key)?.value;return `${get('year')}-${get('month')}-${get('day')}_${get('hour')}${get('minute')}`;};
export function BackupBanner({onNavigate}:{onNavigate:()=>void}){const {isAdmin}=useAuth();const [last,setLast]=useState<string|undefined>(),[ready,setReady]=useState(false),[days,setDays]=useState(7);useEffect(()=>{if(!isAdmin)return;const a=onSnapshot(query(collection(db,'respaldos'),whereComplete(),orderBy('fecha','desc'),limit(1)),s=>{setLast(s.docs[0]?.data().fecha);setReady(true);});const b=onSnapshot(doc(db,'settings','backupParameters'),s=>setDays(s.data()?.warningDays||7));return()=>{a();b();};},[isAdmin]);const age=backupAge(last,days);if(!isAdmin||!ready||age.level==='ok')return null;return <div className="crm78 crm78-note" style={age.level==='danger'?{background:'#fff0f0',borderColor:'#a52632'}:{}}>{age.days===null?'Todavía no registras un respaldo completo.':`Hace ${age.days} días que no respaldas`} <Button onClick={onNavigate}>Respaldar ahora</Button></div>;}
// Solo los respaldos completos actualizan la fecha del banner; una exportación de tabla no cuenta.
import { where } from 'firebase/firestore';
function whereComplete(){return where('tipo','==','completo');}
export function RespaldoView({onOpenProspecto}:{onOpenProspecto:(p:Prospecto)=>void}){
 const {isAdmin,user}=useAuth(),crm=useCRM();const [names,setNames]=useState<string[]>([...BACKUP_COLLECTIONS]),[countsNow,setCounts]=useState<Record<string,number>>({}),[history,setHistory]=useState<any[]>([]),[historyLimit,setHistoryLimit]=useState(100),[restoreHistory,setRestoreHistory]=useState<any[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState<Progress>({message:'',done:0,total:0}),[message,setMessage]=useState(''),[error,setError]=useState(''),[format,setFormat]=useState('zip'),[resume,setResume]=useState(false),[warn,setWarn]=useState(7),[danger,setDanger]=useState(15),[extra,setExtra]=useState('');
 const [table,setTable]=useState('prospectos'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[tableField,setTableField]=useState('fechaRecepcion'),[tableSearch,setTableSearch]=useState('');
 const [file,setFile]=useState<BackupFile|null>(null),[filename,setFilename]=useState(''),[current,setCurrent]=useState<Record<string,BackupRecord[]>>({}),[selected,setSelected]=useState<string[]>([]),[mode,setMode]=useState<'missing'|'replace'>('missing'),[remove,setRemove]=useState(false),[includeUsers,setIncludeUsers]=useState(false),[safety,setSafety]=useState(false),[safetySaved,setSafetySaved]=useState(false),[step,setStep]=useState(0),[confirmText,setConfirmText]=useState(''),[deleteText,setDeleteText]=useState(''),[restoreResult,setRestoreResult]=useState<any>(null),[trashSearch,setTrashSearch]=useState(''),[issues,setIssues]=useState<any[]|null>(null),[integrityRecords,setIntegrityRecords]=useState<Record<string,any>>({}),[integrityDetail,setIntegrityDetail]=useState<{key:string;record:any}|null>(null);
 const [migrationBusy,setMigrationBusy]=useState(false);
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>{if(!isAdmin)return;registeredCollections().then(async list=>{setNames(list);setCounts(await counts(list));}).catch(e=>setError(String(e)));const a=onSnapshot(query(collection(db,'respaldos'),orderBy('fecha','desc'),limit(historyLimit)),s=>setHistory(s.docs.map(d=>({id:d.id,...d.data()}))),e=>setError(e.message));const b=onSnapshot(doc(db,'settings','backupParameters'),s=>{setWarn(s.data()?.warningDays||7);setDanger(s.data()?.dangerDays||15);});const c=onSnapshot(query(collection(db,'logRestauraciones'),orderBy('fecha','desc'),limit(historyLimit)),s=>setRestoreHistory(s.docs.map(d=>({id:d.id,...d.data()}))),e=>setError(e.message));return()=>{a();b();c();controller.current?.abort();};},[isAdmin,historyLimit]);
 const run=async(fn:(s:AbortSignal)=>Promise<void>)=>{if(busy||migrationBusy)return;const control=new AbortController();controller.current=control;setBusy(true);setError('');setMessage('');try{await fn(control.signal);}catch(e){setError(control.signal.aborted?'Operación cancelada. No se generó un respaldo completo. Los lotes de restauración confirmados se conservan.':/resource-exhausted|quota/i.test(String(e))?'Firebase agotó la cuota de esta jornada. La lectura de respaldo conserva su punto de reanudación: vuelve después del reinicio de cuota y marca Reanudar lectura anterior.':String(e));}finally{setBusy(false);}};
 const saveBackup=async(f:BackupFile,safetyBackup=false,signal?:AbortSignal)=>{const name=`${safetyBackup?'seguridad':'respaldo'}_crm_llamadas_${stamp(f.fecha)}`;const chosen=safetyBackup?'json':format;setProgress({message:'Preparando archivos en segundo plano…',done:0,total:1});const blob=await fileJob<Blob>({job:'backup',file:f,name,format:chosen},signal);signal?.throwIfAborted();await download(blob,name+'.'+chosen);if(chosen==='xlsx')return false;await registerBackup(f,blob.size,safetyBackup?'seguridad':'completo');return true;};
 const makeBackup=()=>run(async s=>{const f=await readBackup(s,setProgress,resume);s.throwIfAborted();const official=await saveBackup(f,false,s);if(official){await discardCheckpoint();setResume(false);setMessage('Respaldo completo generado. Conserva el JSON: es el archivo oficial para restaurar.');}else setMessage('Excel generado para consulta. No reemplaza el respaldo JSON oficial.');});
 const loadFile=(input:File)=>run(async s=>{setFile(null);setSafety(false);setSafetySaved(false);setStep(0);setRestoreResult(null);if(input.size>250*1024*1024)throw new Error('El JSON supera 250 MB.');const parsed=await fileJob<BackupFile>({job:'validateFile',input,names},s);const now=await currentFor(parsed,s,setProgress);setFile(parsed);setCurrent(now);setFilename(input.name);setSelected(Object.keys(parsed.collections).filter(n=>!['usuariosAutorizados','respaldos','logRestauraciones','auditoria'].includes(n)));setMessage(parsed.hash?'Archivo válido: hash verificado.':'Archivo válido sin hash: no se puede comprobar su integridad criptográfica.');});
 const securityCopy=()=>run(async s=>{const backup=await readBackup(s,setProgress,false);s.throwIfAborted();await saveBackup(backup,true,s);setCurrent(backup.collections);setSafety(true);setSafetySaved(false);setStep(0);await discardCheckpoint();setMessage('Respaldo de seguridad generado. Verifica que el JSON esté guardado antes de continuar. La vista previa se actualizó con ese estado.');});
 const executeRestore=()=>run(async s=>{if(!file||!safety||!safetySaved||confirmText!=='RESTAURAR'||remove&&deleteText!=='ELIMINAR')throw new Error('Completa todas las confirmaciones y el respaldo de seguridad.');setStep(0);const result=await restore(file,current,selected,mode,remove,includeUsers,s,setProgress,filename);setRestoreResult(result);setSafety(false);setSafetySaved(false);setMessage(`${result.estado}. Aplicados: ${result.aplicados}. Pendientes: ${result.pendientes}.`);});
 const exportTable=(csv:boolean)=>run(async s=>{const canRange=['fechaRecepcion','fechaProspeccion','fechaCita','fechaReporte'].includes(tableField);const constraints=canRange&&(from||to)?[...(from?[where(tableField,'>=',from)]:[]),...(to?[where(tableField,'<=',to)]:[]),orderBy(tableField)]:[];const records=await readPaged(table,s,setProgress,countsNow[table]||0,constraints);const list=records.map(r=>({'ID del documento':r.id,...r.data})).filter((r:any)=>{const d=getDateInLA(r[tableField]);return (!from||d>=from)&&(!to||!!d&&d<=to)&&(!tableSearch||Object.values(r).some(v=>String(v).toLowerCase().includes(tableSearch.toLowerCase())));});await audit('EXPORTAR_TABLA',{coleccion:table,registros:list.length,desde:from,hasta:to,campoFecha:tableField});await download(csv?csvBytes(readable(list)):new Blob([excelBytes(workbook({[table]:readable(list)}))]),`exportacion_${table}_${getTodayInLA()}.${csv?'csv':'xlsx'}`);});
 const permanentDelete=async(p:Prospecto)=>{if(!window.confirm(`Eliminar definitivamente a ${p.nombre} (${p.id}). No se puede deshacer. ¿Continuar?`))return;const typed=window.prompt(`Escribe ELIMINAR ${p.id} para confirmar.`);if(typed!==`ELIMINAR ${p.id}`)return;await run(async s=>{const related=[];for(const name of ['gestiones','citas','retroalimentaciones','ventas']){const snap=await getRelated(name,p.id);if(snap.length)related.push(name);}if(related.length)throw new Error('No se elimina: tiene registros relacionados en '+related.join(', ')+'. Conserva el prospecto archivado para mantener la integridad.');s.throwIfAborted();const batch=writeBatch(db);batch.delete(doc(db,'prospectos',p.id));batch.set(doc(collection(db,'auditoria')),{accion:'ELIMINAR_PROSPECTO',fecha:new Date().toISOString(),usuario:user?.email,idProspecto:p.id});await batch.commit();});};
 if(!isAdmin)return <p>Acceso exclusivo del administrador.</p>;
 const last=history.find(h=>h.tipo==='completo'),age=backupAge(last?.fecha,warn,danger),preview=file?compareBackup(file.collections,current):[];
 return <section className="crm78"><h2>Respaldo y recuperación</h2><MigracionHistoricaView disabled={busy} onBusyChange={setMigrationBusy}/><p className="crm78-note">{PERSONAL_DATA_WARNING}. Los archivos NO se guardan en la app. Consérvalos en un lugar seguro, por ejemplo Google Drive. Los puntos de reanudación temporales quedan en este navegador y puedes eliminarlos.</p>
 {error&&<p className="crm78-error">{error}</p>}{message&&<p className="crm78-status">{message}</p>}{busy&&<div className="crm78-card"><p role="status">{progress.message}</p><progress value={progress.done} max={progress.total||1}/><Button onClick={()=>controller.current?.abort()}>Cancelar en el siguiente lote</Button></div>}
 <div className="crm78-card"><h3>Estado general</h3><p>Último respaldo completo: {last?`${formatDateTimeLA(last.fecha)} · ${last.usuario} · hace ${age.days} días`:'Todavía no hay respaldos completos'}</p>{age.level!=='ok'&&<p className={age.level==='danger'?'crm78-error':'crm78-note'}>{age.days===null?'Crea tu primer respaldo.':`Hace ${age.days} días que no respaldas`}</p>}
 <div className="crm78-toolbar"><label>Aviso amarillo después de <input type="number" min={1} value={warn} onChange={e=>setWarn(Number(e.target.value))}/> días</label><label>Aviso rojo después de <input type="number" min={2} value={danger} onChange={e=>setDanger(Number(e.target.value))}/> días</label><Button disabled={busy||migrationBusy} onClick={()=>run(async()=>{if(warn<1||danger<=warn)throw new Error('El umbral rojo debe superar al amarillo.');await setDoc(doc(db,'settings','backupParameters'),{warningDays:warn,dangerDays:danger});await audit('CONFIGURAR_RESPALDOS',{warn,danger});})}>Guardar avisos</Button><Button disabled={busy||migrationBusy} onClick={()=>run(async()=>setCounts(await counts(names)))}>Actualizar conteos</Button></div>
 <DataTable rows={names.map(n=>({Colección:n,Registros:countsNow[n]??'Pulsa Actualizar conteos'}))}/>
 <p className="crm78-note">Spark limita las lecturas diarias. Paginar no elimina esa cuota. Si se agota, el respaldo se detiene y puede reanudarse en este mismo navegador después del reinicio de cuota. Una lectura de varios días refleja el momento de lectura de cada página: realiza el respaldo y la restauración durante una pausa de trabajo.</p>
 <details><summary>Registro de colecciones</summary><p>Se verifican todas las colecciones conocidas de esta app, incluidas settings y auditorías. Firebase web no enumera colecciones desconocidas ni subcolecciones: registra cualquier colección nueva de primer nivel aquí; también necesita reglas de administrador.</p><input aria-label="Colecciones adicionales" placeholder="Colecciones nuevas separadas por coma" value={extra} onChange={e=>setExtra(e.target.value)}/><Button disabled={busy||migrationBusy} onClick={()=>run(async()=>{const extras=extra.split(',').map(s=>s.trim()).filter(Boolean);if(extras.some(s=>!/^\w+$/.test(s)||/auth|token|secret/i.test(s)))throw new Error('Nombres inválidos o relacionados con autenticación.');const existing=await registeredCollections();const merged=[...new Set([...existing.filter(n=>!BACKUP_COLLECTIONS.includes(n as any)),...extras])];await setDoc(doc(db,'settings','backupRegistry'),{collections:merged});setNames(await registeredCollections());await audit('REGISTRAR_COLECCIONES',{collections:merged});})}>Registrar colecciones</Button></details></div>
 <div className="crm78-card"><h3>Respaldo completo</h3><div className="crm78-toolbar"><select aria-label="Formato de respaldo" value={format} onChange={e=>setFormat(e.target.value)}><option value="zip">JSON oficial + Excel juntos (.zip)</option><option value="json">JSON oficial</option><option value="xlsx">Solo Excel (consulta, no restauración)</option></select><label><input type="checkbox" checked={resume} onChange={e=>setResume(e.target.checked)}/>Reanudar lectura anterior</label><Button disabled={busy||migrationBusy} className="gold" onClick={makeBackup}>Descargar respaldo completo</Button><Button disabled={busy||migrationBusy} onClick={()=>run(async()=>{await discardCheckpoint();setMessage('Punto de reanudación eliminado.');})}>Eliminar punto de reanudación</Button></div></div>
 <div className="crm78-card"><h3>Exportación por tabla</h3><div className="crm78-toolbar"><select aria-label="Colección a exportar" value={table} onChange={e=>setTable(e.target.value)}>{names.map(n=><option key={n}>{n}</option>)}</select><input aria-label="Campo de fecha" value={tableField} onChange={e=>setTableField(e.target.value)} placeholder="Campo de fecha"/><input aria-label="Desde" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="Hasta" type="date" value={to} onChange={e=>setTo(e.target.value)}/><input placeholder="Nombre, estado, propietario…" value={tableSearch} onChange={e=>setTableSearch(e.target.value)}/><Button disabled={busy||migrationBusy} onClick={()=>exportTable(false)}>Exportar a Excel</Button><Button disabled={busy||migrationBusy} onClick={()=>exportTable(true)}>Exportar a CSV</Button></div></div>
 <div className="crm78-card"><h3>Historial de respaldos</h3><DataTable rows={history.map(h=>({Fecha:formatDateTimeLA(h.fecha),Usuario:h.usuario,Tipo:h.tipo,Conteos:JSON.stringify(h.conteos),'Tamaño aproximado':h.tamano,'Hash SHA-256':h.hash}))}/><Button disabled={busy||history.length<historyLimit} onClick={()=>setHistoryLimit(historyLimit+100)}>Cargar respaldos anteriores</Button></div>
 <div className="crm78-card"><h3>Restaurar desde respaldo</h3><input aria-label="Seleccionar respaldo JSON" disabled={busy||migrationBusy} type="file" accept=".json,application/json" onChange={e=>{if(e.target.files?.[0])loadFile(e.target.files[0]);e.target.value='';}}/>
 {file&&<><p>{filename} · {formatDateTimeLA(file.fecha)} · {file.usuario}</p><DataTable rows={preview.map(r=>({Colección:r.coleccion,'En el respaldo':r.respaldo,'En la base actual':r.actual,Nuevos:r.nuevos,Diferentes:r.diferentes,'Solo en la base actual':r.soloActual}))}/><p>Selecciona las colecciones a restaurar. Las fichas de respaldo, restauraciones y auditorías se conservan siempre.</p><div className="crm78-grid">{Object.keys(file.collections).filter(n=>!['respaldos','logRestauraciones','auditoria'].includes(n)).map(n=><label key={n}><span><input type="checkbox" disabled={busy||n==='usuariosAutorizados'&&!includeUsers} checked={selected.includes(n)} onChange={e=>{setSelected(e.target.checked?[...selected,n]:selected.filter(s=>s!==n));setStep(0);}}/>{n}</span></label>)}</div><p><label><input type="checkbox" checked={includeUsers} disabled={busy||migrationBusy} onChange={e=>{setIncludeUsers(e.target.checked);if(!e.target.checked)setSelected(selected.filter(s=>s!=='usuariosAutorizados'));setStep(0);}}/>Incluir explícitamente usuariosAutorizados (el administrador está protegido siempre)</label></p>
 <div className="crm78-toolbar"><select disabled={busy||migrationBusy} aria-label="Modo de restauración" value={mode} onChange={e=>{setMode(e.target.value as any);setRemove(false);setStep(0);}}><option value="missing">Recuperar faltantes: solo crear nuevos</option><option value="replace">Reemplazar con el respaldo</option></select>{mode==='replace'&&<label><input disabled={busy||migrationBusy} type="checkbox" checked={remove} onChange={e=>{setRemove(e.target.checked);setStep(0);}}/>Eliminar lo que no está en el respaldo</label>}</div>
 <p className="crm78-note">Cada lote es atómico. Una operación cancelada o fallida conserva los lotes ya aplicados. Los conflictos de cambios simultáneos detienen la restauración. No existe una transacción única para toda la base; pide al equipo una pausa antes de comenzar.</p><Button disabled={busy||migrationBusy} onClick={securityCopy}>1. Descargar respaldo de seguridad del estado actual</Button>{safety&&<p><label><input type="checkbox" checked={safetySaved} onChange={e=>setSafetySaved(e.target.checked)}/>Verifiqué que el JSON de seguridad terminó de guardarse y lo puedo abrir.</label></p>}<Button disabled={busy||!safety||!safetySaved||!selected.length} onClick={()=>setStep(1)}>2. Revisar resumen y confirmar</Button>
 {step===1&&<Modal title="Confirmar restauración" onClose={()=>setStep(0)}><p>Archivo: {filename}. Modo: {mode==='missing'?'Recuperar faltantes':'Reemplazar'}. Colecciones: {selected.join(', ')}. {remove?'Se eliminarán los registros ausentes del respaldo.':'Se conservan los registros presentes solo en la base actual.'}</p><p>Registros candidatos: {preview.filter(p=>selected.includes(p.coleccion)).reduce((n,p)=>n+(mode==='missing'?p.nuevos:p.respaldo+(remove?p.soloActual:0)),0)}. La cuenta puede excluir registros protegidos.</p><input placeholder="Escribe RESTAURAR" value={confirmText} onChange={e=>setConfirmText(e.target.value)}/>{remove&&<input placeholder="Escribe ELIMINAR como confirmación adicional" value={deleteText} onChange={e=>setDeleteText(e.target.value)}/>}<Button className="danger" disabled={confirmText!=='RESTAURAR'||remove&&deleteText!=='ELIMINAR'||busy} onClick={executeRestore}>Restaurar</Button></Modal>}
 </>}{restoreResult&&<div><p className="crm78-status">{restoreResult.estado}: {restoreResult.aplicados} aplicados, {restoreResult.pendientes} pendientes. {restoreResult.error}</p><DataTable rows={restoreResult.lotes}/>{restoreResult.loteFallido&&<p>Lote {restoreResult.loteFallido}: no aplicado. Los siguientes tampoco se aplicaron.</p>}</div>}
 <h3>Historial de restauraciones</h3><DataTable rows={restoreHistory.map(r=>({Fecha:formatDateTimeLA(r.fecha),Usuario:r.usuario,Archivo:r.archivo,Modo:r.modo,Estado:r.estado,Aplicados:r.aplicados,Pendientes:r.pendientes??r.total-r.aplicados,Lotes:JSON.stringify(r.lotes),Error:r.error||''}))}/><Button disabled={busy||restoreHistory.length<historyLimit} onClick={()=>setHistoryLimit(historyLimit+100)}>Cargar restauraciones anteriores</Button></div>
 <div className="crm78-card"><h3>Papelera</h3><input placeholder="Buscar prospectos archivados" value={trashSearch} onChange={e=>setTrashSearch(e.target.value)}/><DataTable rows={crm.prospectos.filter(p=>p.archivado&&`${p.nombre} ${p.telefono} ${p.id}`.toLowerCase().includes(trashSearch.toLowerCase())).map((p:any)=>({ID:p.id,Nombre:p.nombre,Teléfono:p.telefono,Motivo:p.motivoArchivo||p.observacion||'Sin motivo registrado',Quién:p.archivadoPor||p.modificadoPor||'No registrado',Cuándo:formatDateTimeLA(p.archivadoEn||p.modificadoEn),Recuperar:'Recuperar',Eliminar:'Eliminar definitivamente'}))} onCell={(r,k)=>{const p=crm.prospectos.find(p=>p.id===r.ID)!;if(k==='Recuperar')run(async()=>{const result=await crm.archiveProspecto(p.id,false);if(!result.success)throw new Error(result.error);await audit('RECUPERAR_PROSPECTO',{idProspecto:p.id});});else if(k==='Eliminar')permanentDelete(p);else onOpenProspecto(p);}}/></div>
 <div className="crm78-card"><h3>Verificación de integridad</h3><Button disabled={busy||migrationBusy} onClick={()=>run(async s=>{const all:any={};for(const name of ['prospectos','gestiones','citas','ventas','retroalimentaciones'])all[name]=(await readPaged(name,s,setProgress,countsNow[name]||0)).map(r=>({...r.data,id:r.id}));const found=inspectCRMIntegrity(all,crm.settings.telemarketingAgents.map(a=>a.name));setIssues(found);const byCollection=Object.fromEntries(Object.entries(all).map(([name,rows])=>[name,new Map((rows as any[]).map(r=>[r.id,r]))]));setIntegrityRecords(Object.fromEntries(found.map(i=>[i.coleccion+'/'+i.id,byCollection[i.coleccion].get(i.id)])));})}>Revisar datos</Button>{issues&&<><p>{issues.length} problemas encontrados. No se corrige nada automáticamente.</p><Button disabled={busy||migrationBusy} onClick={()=>run(async()=>{await audit('EXPORTAR_INTEGRIDAD',{problemas:issues.length});await download(new Blob([excelBytes(workbook({Integridad:readable(issues!)}))]),`integridad_${getTodayInLA()}.xlsx`);})}>Exportar informe a Excel</Button><DataTable rows={readable(issues)} onCell={r=>{const p=crm.prospectos.find(p=>p.id===r['ID de prospecto']);if(p)onOpenProspecto(p);else {const key=r.coleccion+'/'+r.ID;setIntegrityDetail({key,record:integrityRecords[key]});}}}/></>}</div>
 {integrityDetail&&<Modal title={'Registro · '+integrityDetail.key} onClose={()=>setIntegrityDetail(null)}><p>Este registro no tiene un prospecto existente para abrir. Se muestra sin modificarlo.</p><DataTable rows={readable([integrityDetail.record||{}])}/></Modal>}
 <div className="crm78-card"><h3>Automatización futura</h3><p>Si en el futuro activas facturación, puedes evaluar la exportación administrada de Firestore a un bucket de Google Cloud Storage, programada mediante Cloud Scheduler y un servicio autorizado con IAM. Esto requiere configurar permisos, retención, costos y alertas. Esta versión Spark no crea ni ejecuta esa automatización.</p></div>
 </section>;
}
import { getDocs } from 'firebase/firestore';
async function getRelated(name:string,id:string){return (await getDocs(query(collection(db,name),where('idProspecto','==',id),limit(1)))).docs;}
