import React,{useMemo,useState,useRef} from 'react';
import { useCRM } from '../context/CRMContext';
import { useAuth } from '../context/AuthContext';
import { ownerSimilarity,normalizeOwner } from '../businessRules';
import { updateInChunks } from '../stage78/service';
import { Button,DataTable,Modal } from '../stage78/ui';
export function UnificarPropietarios(){const {isAdmin,user}=useAuth(),{prospectos}=useCRM();const [pair,setPair]=useState<string[]|null>(null),[name,setName]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const control=useRef<AbortController|null>(null);
 const pairs=useMemo(()=>{if(!isAdmin)return [];const names=[...new Set(prospectos.map(p=>p.propietario).filter(Boolean))];const buckets=new Map<string,string[]>();for(const n of names){const key=normalizeOwner(n).split(' ')[0];const list=buckets.get(key)||[];list.push(n);buckets.set(key,list);}const result:any[]=[];for(const bucket of buckets.values())for(let i=0;i<bucket.length;i++)for(let j=i+1;j<bucket.length;j++)if(ownerSimilarity(bucket[i],bucket[j]))result.push({Nombre:bucket[i],Variante:bucket[j],Registros:prospectos.filter(p=>p.propietario===bucket[i]||p.propietario===bucket[j]).length});return result;},[prospectos,isAdmin]);if(!isAdmin)return null;
 return <div className="crm78 crm78-card"><h3>Unificar propietarios</h3><p>Los reportes ya agrupan sin mayúsculas, tildes ni espacios sobrantes. Esta herramienta cambia los nombres guardados; revisa cada propuesta para evitar unir personas distintas.</p>{message&&<p className="crm78-status">{message}</p>}<DataTable rows={pairs} onCell={r=>{setPair([r.Nombre,r.Variante]);setName(r.Nombre.trim());setConfirm('');}}/>{pair&&<Modal title="Unificar nombres de propietario" onClose={()=>{if(!busy)setPair(null);}}><p>{pair.join(' ↔ ')}</p><input aria-label="Nombre correcto" value={name} onChange={e=>setName(e.target.value)}/><p>Escribe UNIFICAR y confirma el resumen antes de guardar.</p><input placeholder="UNIFICAR" value={confirm} onChange={e=>setConfirm(e.target.value)}/><Button disabled={busy||confirm!=='UNIFICAR'||!name.trim()} onClick={async()=>{const selected=prospectos.filter(p=>pair.includes(p.propietario));if(!window.confirm(`Se actualizarán ${selected.length} prospectos a «${name.trim()}». ¿Confirmar?`))return;setBusy(true);control.current=new AbortController();try{const count=await updateInChunks('prospectos',selected.map(p=>({id:p.id,data:{propietario:name.trim(),modificadoEn:new Date().toISOString(),modificadoPor:user?.email}})),'UNIFICAR_PROPIETARIOS',control.current.signal,{nombresAnteriores:pair,nombreCorrecto:name.trim()});setMessage(`${count} prospectos actualizados.`);setPair(null);}catch(e){setMessage(String(e));}finally{setBusy(false);}}}>Confirmar y unificar</Button>{busy&&<Button onClick={()=>control.current?.abort()}>Cancelar al terminar el lote</Button>}</Modal>}</div>;
}
